### PR TITLE
lib.rs: docs: include_str!(README) instead of copying all out

### PR DESCRIPTION
**Pull request by explosion-mental**
_debloats_ lib.rs a bit, while keeping only one source up to date.

### CODE REVIEW

**Comment by Atreyagaurav** [comment]
Problem with this is, if the docs don't have these kinda lines 
```
# use std::error::Error;
# use std::collections::HashMap;
# use std::path::PathBuf;
```
then the `cargo test` fails. But if you keep them in the README.md, then the documentation in README.md looks weird in github. That's why there are two copies one with those lines in the `lib.rs` and curated ones in README.md.

It'd be nice if we could generate README.md from the rust docs instead, probably. But yeah, having one copy would be great, let me know if you a solution to that.

**Comment by Atreyagaurav** [comment]
https://docs.rs/cargo-readme/latest/cargo_readme/ 

This seems to do the reverse, which is excellent. The docs will be used to generate README.md, so I'll be generating README from the docs now.

**Comment by explosion-mental** [comment]
Now that I think about it, I'm not sure whether you want the whole readme in lib.rs.

**Comment by Atreyagaurav** [comment]
Definitely not. I think might as well just write a short README that focuses on general usages and other details and link to `docs.rs` for the library usage. Will do that in the next iteration.

**Pull request closed without merging**
